import { Ad } from "@/types/database";

export function generateCreativeGuidelines(
  ads: Ad[],
  options: {
    brandName?: string;
    productType?: string;
    additionalContext?: string;
  } = {}
): string {
  const topAds = ads.slice(0, 20);
  const creativeTypes = [...new Set(topAds.map((ad) => ad.creative_type).filter(Boolean))];
  const ctaTypes = [...new Set(topAds.map((ad) => ad.call_to_action).filter(Boolean))];

  const avgMetrics = {
    roas: topAds.reduce((s, a) => s + a.roas, 0) / topAds.length,
    ctr: topAds.reduce((s, a) => s + a.ctr, 0) / topAds.length,
    cpc: topAds.reduce((s, a) => s + a.cpc, 0) / topAds.length,
  };

  const imageAds = topAds.filter((a) => a.creative_type === "image");
  const videoAds = topAds.filter((a) => a.creative_type === "video");

  const adSummaries = topAds
    .slice(0, 10)
    .map((ad, i) => {
      const details = [
        `${i + 1}. "${ad.name || "Untitled"}" - ${ad.creative_type || "unknown"} format`,
        `   ROAS: ${ad.roas.toFixed(2)}x | CTR: ${ad.ctr.toFixed(2)}% | Spend: $${ad.spend.toFixed(2)}`,
      ];
      if (ad.headline) details.push(`   Headline: "${ad.headline}"`);
      if (ad.call_to_action) details.push(`   CTA: ${ad.call_to_action}`);
      return details.join("\n");
    })
    .join("\n");

  return `# ${options.brandName || "[Brand Name]"} - Creative Brand Guidelines
## Generated from Top-Performing Ad Creative Analysis

---

## 1. Overview
These guidelines are derived from an analysis of ${topAds.length} top-performing ad creatives${options.productType ? ` for ${options.productType}` : ""}. They represent the visual and creative patterns that have proven to drive the best performance metrics.

### Performance Benchmarks (from analyzed ads)
- Average ROAS: ${avgMetrics.roas.toFixed(2)}x
- Average CTR: ${avgMetrics.ctr.toFixed(2)}%
- Average CPC: $${avgMetrics.cpc.toFixed(2)}

---

## 2. Creative Formats
### Winning Formats
${creativeTypes.map((t) => `- **${t}**: Used in ${topAds.filter((a) => a.creative_type === t).length} top-performing ads`).join("\n")}

### Format Distribution
- Image ads: ${imageAds.length} (${((imageAds.length / topAds.length) * 100).toFixed(0)}%)
- Video ads: ${videoAds.length} (${((videoAds.length / topAds.length) * 100).toFixed(0)}%)

### Recommendations
- Primary format: ${creativeTypes[0] || "image"} (highest performer)
- Always test both static and video formats
- Ensure creative is optimized for mobile-first viewing

---

## 3. Visual Style Guidelines

### Composition
When creating new ad creative for this brand, follow these principles derived from top performers:
- Use clean, uncluttered compositions that highlight the product
- Maintain consistent visual branding across all ad formats
- Ensure the key message is visible within the first 3 seconds (for video) or at a glance (for images)

### Color & Branding
- Maintain brand color consistency across all creative
- Use contrast effectively to draw attention to CTAs and key messaging
- Ensure brand logo/identity is present but not overwhelming

### Text Overlay (if applicable)
- Keep text overlay minimal (Facebook's 20% text rule)
- Use large, readable fonts for any on-image text
- Ensure text is legible on mobile devices

---

## 4. Call-to-Action Guidelines
### Proven CTAs
${ctaTypes.map((cta) => `- **${cta}**: Used in ${topAds.filter((a) => a.call_to_action === cta).length} winning ads`).join("\n") || "- Various CTAs used across winning ads"}

### CTA Best Practices
- Match CTA to campaign objective (SHOP_NOW for purchase, LEARN_MORE for awareness)
- Ensure CTA button is prominent and clearly visible
- Test multiple CTAs against each other

---

## 5. Top-Performing Ad Reference
${adSummaries}

---

## 6. Creative Production Checklist
- [ ] Follows brand visual guidelines above
- [ ] Uses proven creative format (${creativeTypes[0] || "image/video"})
- [ ] Includes appropriate CTA (${ctaTypes[0] || "SHOP_NOW"})
- [ ] Optimized for mobile viewing
- [ ] Text is minimal and readable
- [ ] Brand identity is present
- [ ] Creative is original (not a direct copy of existing ads)
- [ ] Multiple variations prepared for testing

${options.additionalContext ? `\n---\n\n## 7. Additional Notes\n${options.additionalContext}` : ""}

---

*Generated by Adalyzer from analysis of ${topAds.length} top-performing ad creatives.*`;
}

export function generateCopyGuidelines(
  ads: Ad[],
  options: {
    brandName?: string;
    productType?: string;
    tone?: string;
    additionalContext?: string;
  } = {}
): string {
  const topAds = ads.slice(0, 20).filter((ad) => ad.primary_text || ad.headline);

  const avgMetrics = {
    roas: topAds.reduce((s, a) => s + a.roas, 0) / topAds.length,
    ctr: topAds.reduce((s, a) => s + a.ctr, 0) / topAds.length,
  };

  // Analyze copy patterns
  const texts = topAds.map((ad) => ad.primary_text || "").filter(Boolean);
  const headlines = topAds.map((ad) => ad.headline || "").filter(Boolean);
  const avgTextLength = Math.round(texts.reduce((s, t) => s + t.length, 0) / Math.max(texts.length, 1));
  const avgHeadlineLength = Math.round(headlines.reduce((s, h) => s + h.length, 0) / Math.max(headlines.length, 1));

  const allText = texts.join(" ").toLowerCase();
  const hasEmojis = /[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{2600}-\u{26FF}]/u.test(allText);
  const hasQuestions = texts.filter((t) => t.includes("?")).length;
  const hasNumbers = texts.filter((t) => /\d+%|\d+x|\$\d+/.test(t)).length;
  const hasLineBreaks = texts.filter((t) => t.includes("\n")).length;

  const copyExamples = topAds
    .slice(0, 8)
    .map((ad, i) => {
      const lines = [`### Example ${i + 1} (ROAS: ${ad.roas.toFixed(2)}x)`];
      if (ad.headline) lines.push(`**Headline:** ${ad.headline}`);
      if (ad.primary_text) lines.push(`**Body:** ${ad.primary_text.slice(0, 300)}${ad.primary_text.length > 300 ? "..." : ""}`);
      if (ad.call_to_action) lines.push(`**CTA:** ${ad.call_to_action}`);
      return lines.join("\n");
    })
    .join("\n\n");

  return `# ${options.brandName || "[Brand Name]"} - Ad Copy & Voice Guidelines
## Generated from Top-Performing Ad Copy Analysis

---

## 1. Brand Voice Overview
These guidelines capture the voice, tone, and messaging patterns proven to drive the best ad performance${options.productType ? ` for ${options.productType}` : ""}.${options.tone ? ` Core tone: **${options.tone}**.` : ""}

### Performance Benchmarks
- Average ROAS: ${avgMetrics.roas.toFixed(2)}x
- Average CTR: ${avgMetrics.ctr.toFixed(2)}%
- Analyzed: ${topAds.length} top-performing ad copies

---

## 2. Copy Structure & Length

### Primary Text (Body Copy)
- **Optimal length:** ~${avgTextLength} characters
- **Line breaks:** ${hasLineBreaks > topAds.length / 2 ? "Frequently used" : "Minimal"} (${hasLineBreaks}/${topAds.length} top ads use them)
- **Format:** ${avgTextLength > 200 ? "Long-form storytelling" : avgTextLength > 100 ? "Medium-form with key points" : "Short, punchy copy"}

### Headlines
- **Optimal length:** ~${avgHeadlineLength} characters
- Keep headlines concise and benefit-driven
- Front-load the most important information

---

## 3. Messaging Patterns

### Proven Techniques
- **Questions:** ${hasQuestions > 0 ? `Used in ${hasQuestions}/${topAds.length} top ads - effective for engagement` : "Rarely used"}
- **Emojis:** ${hasEmojis ? "Used in top-performing copy - adds visual interest and breaks up text" : "Not typically used - brand maintains a clean text style"}
- **Numbers/Stats:** ${hasNumbers > 0 ? `Used in ${hasNumbers}/${topAds.length} top ads - adds credibility and specificity` : "Rarely used"}

### Hook Types (first line strategies)
When writing the opening line, consider these proven approaches from top performers:
1. **Problem-Solution:** Address a pain point, then present the solution
2. **Social Proof:** Lead with results, testimonials, or popularity
3. **Curiosity:** Ask a compelling question or make an intriguing statement
4. **Direct Benefit:** State the primary value proposition immediately
5. **Urgency:** Create time-sensitivity or scarcity

---

## 4. Tone & Voice Rules

### DO:
- Write in a ${options.tone || "conversational yet professional"} tone
- Focus on benefits over features
- Use specific, concrete language
- Include a clear value proposition
- Match the audience's language and concerns

### DON'T:
- Use excessive jargon or industry-speak
- Make unsubstantiated claims
- Write walls of text without visual breaks
- Use aggressive or pushy language
- Ignore the emotional aspect of the purchase decision

---

## 5. Top-Performing Copy Examples
${copyExamples}

---

## 6. Copy Testing Framework

### Variables to Test
1. **Hook/Opening line** - Test different opening approaches
2. **Length** - Short vs. medium vs. long-form
3. **Tone** - Emotional vs. rational
4. **Social proof** - With vs. without
5. **CTA language** - Direct vs. soft

### Copy Production Checklist
- [ ] Follows brand voice guidelines above
- [ ] Uses proven messaging patterns
- [ ] Appropriate length (~${avgTextLength} chars for body)
- [ ] Strong opening hook
- [ ] Clear value proposition
- [ ] Compelling CTA
- [ ] Multiple variations for A/B testing
- [ ] Proofread for errors

${options.additionalContext ? `\n---\n\n## 7. Additional Notes\n${options.additionalContext}` : ""}

---

*Generated by Adalyzer from analysis of ${topAds.length} top-performing ad copies.*`;
}
